//var a = "成功"

try{
    console.log(a)
}catch{
    console.log(ug);
}finally{
    console.log("成功")
}

throw new Error(a);